// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCarzUNjyW5VkvmJVUS5UDtMGUOu2lqOxM',
    appId: '1:325488942058:web:b078322c99bf7a6a10f093',
    messagingSenderId: '325488942058',
    projectId: 'toktik-3b7e1',
    authDomain: 'toktik-3b7e1.firebaseapp.com',
    databaseURL: 'https://toktik-3b7e1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'toktik-3b7e1.appspot.com',
    measurementId: 'G-SKMDFBESQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSL__yGxbSBrEFBBHoQyntFtJK_JW807c',
    appId: '1:325488942058:android:fc6ab7a26bf4d27c10f093',
    messagingSenderId: '325488942058',
    projectId: 'toktik-3b7e1',
    databaseURL: 'https://toktik-3b7e1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'toktik-3b7e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvli5LHYfWCu0yQsl7q_QgmYysd8cqvqQ',
    appId: '1:325488942058:ios:a8d2aee4e59b7f5c10f093',
    messagingSenderId: '325488942058',
    projectId: 'toktik-3b7e1',
    databaseURL: 'https://toktik-3b7e1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'toktik-3b7e1.appspot.com',
    iosBundleId: 'com.example.toktik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvli5LHYfWCu0yQsl7q_QgmYysd8cqvqQ',
    appId: '1:325488942058:ios:2d452ee7a141f40510f093',
    messagingSenderId: '325488942058',
    projectId: 'toktik-3b7e1',
    databaseURL: 'https://toktik-3b7e1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'toktik-3b7e1.appspot.com',
    iosBundleId: 'com.example.toktik.RunnerTests',
  );
}
